project_name: builder

release:
  github:
    owner: jtarchie
    name: builder

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - "386"
    - amd64
    - arm
    - arm64
    - ppc64
  goarm:
    - "7"
  ignore:
    - goos: windows
      goarch: arm
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=goreleaser

universal_binaries:
- replace: false

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
    - goos: windows
      format: zip
    builds_info:
      group: root
      owner: root
    rlcp: true
    files:
      - README.md
      - LICENSE.md
      - completions/*
      - manpages/*

brews:
- tap:
    owner: jtarchie
    name: builder
  ids:
  - homebrew
  test: |
    system "#{bin}/builder --help"
  install:
    bin.install "builder"
checksum:
  name_template: 'checksums.txt'
changelog:
  skip: true