version: '3'

tasks:
  build: go build ./...
  format:
    cmds:
    - gofmt -w .
  lint: golangci-lint run --fix --timeout "10m"
  test: go test -race ./...
  default:
    cmds:
    - task: format
    - task: build
    - task: test