version: '3'

tasks:
  build: go build ./...
  format:
    cmds:
    - deno fmt README.md
    - gofmt -w .
  lint: golangci-lint run --fix --timeout "10m"
  test: go test -cover -race ./...
  example: go run ./... --source-path example/ --build-path ./build
  default:
    cmds:
    - task: format
    - task: lint
    - task: build
    - task: test
    - task: example